spring.application.name=api-gateway
server.port=8080

# Enable discovery for dynamic routing
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Register to Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Optional: Logging
logging.level.org.springframework.cloud.gateway=DEBUG